# mypy: disable-error-code="no-untyped-def,type-arg,misc"

import enum
from typing import Any, Callable, ClassVar

import _cython_3_0_10

__reduce_cython__: _cython_3_0_10.cython_function_or_method
__setstate_cython__: _cython_3_0_10.cython_function_or_method
__test__: dict
nvrtcAddNameExpression: _cython_3_0_10.cython_function_or_method
nvrtcCompileProgram: _cython_3_0_10.cython_function_or_method

# nvrtcCreateProgram: _cython_3_0_10.cython_function_or_method
def nvrtcCreateProgram(
    src: bytes,
    name: bytes,
    numHeaders: int,
    headers: list[bytes],
    includes: list[bytes],
) -> tuple[nvrtcResult, nvrtcProgram]: ...

nvrtcDestroyProgram: _cython_3_0_10.cython_function_or_method
nvrtcGetCUBIN: _cython_3_0_10.cython_function_or_method
nvrtcGetCUBINSize: _cython_3_0_10.cython_function_or_method
nvrtcGetErrorString: _cython_3_0_10.cython_function_or_method
nvrtcGetLTOIR: _cython_3_0_10.cython_function_or_method
nvrtcGetLTOIRSize: _cython_3_0_10.cython_function_or_method
nvrtcGetLoweredName: _cython_3_0_10.cython_function_or_method
nvrtcGetNVVM: _cython_3_0_10.cython_function_or_method
nvrtcGetNVVMSize: _cython_3_0_10.cython_function_or_method
nvrtcGetNumSupportedArchs: _cython_3_0_10.cython_function_or_method
nvrtcGetOptiXIR: _cython_3_0_10.cython_function_or_method
nvrtcGetOptiXIRSize: _cython_3_0_10.cython_function_or_method
nvrtcGetPTX: _cython_3_0_10.cython_function_or_method

# nvrtcGetPTXSize: _cython_3_0_10.cython_function_or_method
def nvrtcGetPTXSize(prog: nvrtcProgram) -> tuple[nvrtcResult, int]: ...

# nvrtcGetProgramLog: _cython_3_0_10.cython_function_or_method
def nvrtcGetProgramLog(prog: nvrtcProgram, log: bytes) -> tuple[nvrtcResult]: ...

# nvrtcGetProgramLogSize: _cython_3_0_10.cython_function_or_method
def nvrtcGetProgramLogSize(prog: nvrtcProgram) -> tuple[nvrtcResult, int]: ...

nvrtcGetSupportedArchs: _cython_3_0_10.cython_function_or_method
nvrtcVersion: _cython_3_0_10.cython_function_or_method
sizeof: _cython_3_0_10.cython_function_or_method

class nvrtcProgram:
    def __init__(self, *args, **kwargs) -> Any: ...
    def getPtr(self) -> Any: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __reduce__(self): ...

class nvrtcResult(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    NVRTC_ERROR_BUILTIN_OPERATION_FAILURE: ClassVar[nvrtcResult] = ...
    NVRTC_ERROR_COMPILATION: ClassVar[nvrtcResult] = ...
    NVRTC_ERROR_INTERNAL_ERROR: ClassVar[nvrtcResult] = ...
    NVRTC_ERROR_INVALID_INPUT: ClassVar[nvrtcResult] = ...
    NVRTC_ERROR_INVALID_OPTION: ClassVar[nvrtcResult] = ...
    NVRTC_ERROR_INVALID_PROGRAM: ClassVar[nvrtcResult] = ...
    NVRTC_ERROR_NAME_EXPRESSION_NOT_VALID: ClassVar[nvrtcResult] = ...
    NVRTC_ERROR_NO_LOWERED_NAMES_BEFORE_COMPILATION: ClassVar[nvrtcResult] = ...
    NVRTC_ERROR_NO_NAME_EXPRESSIONS_AFTER_COMPILATION: ClassVar[nvrtcResult] = ...
    NVRTC_ERROR_OUT_OF_MEMORY: ClassVar[nvrtcResult] = ...
    NVRTC_ERROR_PROGRAM_CREATION_FAILURE: ClassVar[nvrtcResult] = ...
    NVRTC_ERROR_TIME_FILE_WRITE_FAILED: ClassVar[nvrtcResult] = ...
    NVRTC_SUCCESS: ClassVar[nvrtcResult] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...
